// Code generated by "stringer -type=BumpType -output=bump_type_string.go"; DO NOT EDIT.

package semver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecific-0]
	_ = x[Major-1]
	_ = x[Minor-2]
	_ = x[Patch-3]
}

const _BumpType_name = "UnspecificMajorMinorPatch"

var _BumpType_index = [...]uint8{0, 10, 15, 20, 25}

func (i BumpType) String() string {
	if i < 0 || i >= BumpType(len(_BumpType_index)-1) {
		return "BumpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BumpType_name[_BumpType_index[i]:_BumpType_index[i+1]]
}
