name: Build

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**.png'
    - '**.md'
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**.png'
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - uses: magefile/mage-action@v1
      with:
        args: test
