name: Build

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.17.x

    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/go/bin
          ~/.cache/golangci-lint
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-

    - name: check tools
      id: check_tools
      uses: andstor/file-existence-action@v1
      with:
        files: '/home/runner/go/bin/mage, /home/runner/go/bin/golangci-lint, /home/runner/go/bin/tparse'

    - name: setup tools
      if: steps.check_tools.outputs.files_exists != 'true'
      run: go run ./tool/mage.go setup

    - name: test
      run: mage test

    - uses: codecov/codecov-action@v2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./codecov.out
        flags: tests
        name: main-tests

