name: CodeQL

on:
  push:
    branches:
    - main
    paths-ignore:
    - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
    - '**.md'
  schedule:
  - cron: '0 10 * * 0'

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: github/codeql-action/init@v2
      with:
        languages: go
    - uses: github/codeql-action/autobuild@v2
    - uses: github/codeql-action/analyze@v2
